# Настройки aider для работы с LM Studio
model: openai/qwen3-coder-30b
openai-api-base: http://localhost:1234/v1
openai-api-key: lm-studio

# Языки
chat-language: ru
commit-language: en

# Ограничения токенов (настройте под свой контекст)
max-chat-history-tokens: 16000
map-tokens: 2000

# Поведение
auto-commits: true
gitignore: true
pretty: true
stream: true

# Автоподтверждения
yes-always: true

# Цвета (опционально)
dark-mode: true
